sudo: required
language: R
cache: packages
r_github_packages:
- johndharrison/webpagetestr
env:
  matrix:
  - NOT_CRAN=true
r:
- oldrel
- release
- devel
after_success:
- Rscript -e 'covr::codecov()'
