sudo: required
language: R
cache: packages
r_github_packages:
- johndharrison/HARtools
- johndharrison/webpagetestr
r_packages:
- png
- jpeg
env:
  matrix:
  - NOT_CRAN=true
r:
- oldrel
- release
- devel
after_success:
- Rscript -e 'covr::codecov()'
